# Dockerfile.gpu
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

WORKDIR /app

# 设置非交互模式，避免安装时卡在时区选择
ENV DEBIAN_FRONTEND=noninteractive

# 安装必要的系统组件和 Miniconda
RUN apt-get update && apt-get install -y wget bzip2 ca-certificates gcc g++ libpq-dev git && \
    rm -rf /var/lib/apt/lists/* && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh

# 把 Conda 加入环境变量
ENV PATH=/opt/conda/bin:$PATH

# 复制 GPU 配置文件
COPY environment_gpu.yml .

# 创建 Conda 环境
RUN conda env create -f environment_gpu.yml

# 告诉 Docker 后续的命令都在 cssa-ai 环境里执行
SHELL ["conda", "run", "-n", "cssa-ai", "/bin/bash", "-c"]

COPY . .

# 设置入口点：自动激活 Conda 环境
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "cssa-ai"]

CMD ["tail", "-f", "/dev/null"]