name: cssa-ai
channels:
  - conda-forge
  - pytorch   # add pytorch channel for reliable PyTorch/torchvision/torchaudio builds
  - defaults
dependencies:
  - python=3.11.12
  - mypy
  - matplotlib
  - numpy
  - pandas
  - ipykernel
  - jupyter
  - scikit-learn
  - nltk
  - gensim
  - ipython
  - tqdm
  - faiss-cpu>=1.7.4
  - pytorch
  - torchvision
  - torchaudio
  # If you are on CPU-only, uncomment this line (Linux/Windows):
  # - cpuonly
  # On Apple Silicon you can omit cpuonly; PyTorch uses MPS automatically if available.
  - pip
  - pip:
      - sentence_transformers
      - accelerate==1.6.0
      - rank-bm25==0.2.2
      - discopy
      - langchain-community
      - langchain-text-splitters
      - trafilatura
      - langdetect
      - hanzidentifier
      - bs4
      - requests