from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_DIR = PROJECT_ROOT / "data"
DEFAULT_RAW_DATA_DIR = DEFAULT_DATA_DIR / "raw"
DEFAULT_PROCESSED_DATA_DIR = DEFAULT_DATA_DIR / "processed"
DEFAULT_CURRENT_DATA_DIR = DEFAULT_DATA_DIR / "current"
DEFAULT_WECHAT_RAW_DIR = DEFAULT_RAW_DATA_DIR / "wechat"
DEFAULT_KNOWLEDGE_BASE_PROCESSED_DIR = (
    DEFAULT_PROCESSED_DATA_DIR / "knowledge_base"
)
DEFAULT_WECHAT_RAW_CURRENT = (
    DEFAULT_CURRENT_DATA_DIR / "wechat_articles_all.json"
)
DEFAULT_KNOWLEDGE_BASE_CURRENT = (
    DEFAULT_CURRENT_DATA_DIR / "wechat_articles_processed.json"
)
LEGACY_WECHAT_RAW_INPUT = DEFAULT_DATA_DIR / "wechat_articles_all.json"
LEGACY_KNOWLEDGE_BASE_INPUT = (
    DEFAULT_DATA_DIR / "wechat_articles_processed.json"
)
DEFAULT_WECHAT_RAW_INPUT = DEFAULT_WECHAT_RAW_CURRENT
DEFAULT_KNOWLEDGE_BASE_INPUT = (
    DEFAULT_KNOWLEDGE_BASE_CURRENT
)
