retriever:
  embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  top_k: 5

pgvector:
  table_name: knowledge_base

faiss:
  index_path: data/faiss/index.faiss
  embedding_path: data/faiss/question_embeddings.pt
  idmap_path: data/faiss/id_mapping.json

generator:
  llm_model: gpt-4o-mini